<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Первая веб Операционная система</title>  
        <link rel="stylesheet" href="css/main/style.css">
    </head>
    <body>
        <form id ="loginForm">
            <input type="text" name="username" id="username"><br>
            <input type="text" name="username" id="password"><br>
            <input type="submit" id ="submit"><a href ="/userinterface/">next</a>
        </form>
    </body>
</html>