<br /><br />
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
        <ul class="nav nav-tabs nav-stacked">
            <li class="active"><a href="#">Список экскурсий</a></li>
            <li><a href="#">Создать экскурсию</a></li>
            <li style="position:relative;"><a href="#">Заказанные экскурсии</a>
                <div class="popover top" style="display:block; left:149px; top:-18px;">
            <div class="arrow"></div>
            <div class="popover-content">
              3
            </div>
          </div>
            </li>
        </ul>


    </div>
    <div class="span9">
        <table class="table table-striped">
              <thead>
                <tr>
                  <th>№</th>
                  <th>Название</th>
                  <th>Длительность</th>
                  <th>Кол. Чел.</th>
                  <th>Цена (UAH)</th>
                  <th>Дата</th>
                  <th>Статус</th>
                  <th style="width:85px;"></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>20</td>
                  <td>50</td>
                  <td>03.05.2913</td>
                  <td>Статус</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                
                <tr>
                  <td>2</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>20</td>
                  <td>50</td>
                  <td>03.05.2913</td>
                  <td>Статус</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                
                <tr>
                  <td>3</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>20</td>
                  <td>50</td>
                  <td>03.05.2913</td>
                  <td>Статус</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                
                <tr>
                  <td>4</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>20</td>
                  <td>50</td>
                  <td>03.05.2913</td>
                  <td>Статус</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                
                <tr>
                  <td>5</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>20</td>
                  <td>50</td>
                  <td>03.05.2913</td>
                  <td>Статус</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
              </tbody>
            </table>
        <div class="pagination pagination-centered">
              <ul>
                <li class="disabled"><a href="#">«</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">»</a></li>
             </ul>
            </div>
        
    </div>
  </div>
</div>