<br /><br />
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
        <ul class="nav nav-tabs nav-stacked">
            <li class="active"><a href="#">Список экскурсий</a></li>
            <li><a href="#">Создать экскурсию</a></li>
            <li><a href="#">Заказанные экскурсии</a></li>
        </ul>


    </div>
    <div class="span9">
        <table class="table table-striped">
              <thead>
                <tr>
                  <th>№</th>
                  <th>Название</th>
                  <th>Длительность</th>
                  <th>Цена</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1</td>
                  <td>Mark</td>
                  <td>Otto</td>
                  <td>@mdo</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td>Larry</td>
                  <td>the Bird</td>
                  <td>@twitter</td>
                </tr>
                                <tr>
                  <td>4</td>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
                </tr>
                                <tr>
                  <td>5</td>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
                </tr>
                                <tr>
                  <td>6</td>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
                </tr>
                                <tr>
                  <td>7</td>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
                </tr>
                                <tr>
                  <td>8</td>
                  <td>Jacob</td>
                  <td>Thornton</td>
                  <td>@fat</td>
                </tr>
              </tbody>
            </table>
        <div class="pagination pagination-centered">
              <ul>
                <li class="disabled"><a href="#">«</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">»</a></li>
             </ul>
            </div>
    </div>
  </div>
</div>