<br /><br />
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
        <ul class="nav nav-tabs nav-stacked">
            <li class="active"><a href="#">Список экскурсий</a></li>
            <li><a href="#">Создать экскурсию</a></li>
            <li><a href="#">Заказанные экскурсии</a></li>
        </ul>


    </div>
    <div class="span9">
        <table class="table table-striped">
              <thead>
                <tr>
                  <th>№</th>
                  <th>Название</th>
                  <th>Длительность</th>
                  <th>Цена (UAH)</th>
                  <th style="width:85px;"></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Исторический музей</td>
                  <td>2 часа</td>
                  <td>100</td>
                  <td><button type="button" class="btn"><i class="icon-pencil"></i></button>
                  <button type="button" class="btn"><i class="icon-trash"></i></button></td>
                </tr>
              </tbody>
            </table>
        <div class="pagination pagination-centered">
              <ul>
                <li class="disabled"><a href="#">«</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">»</a></li>
             </ul>
            </div>
        
    </div>
  </div>
</div>