<!DOCTYPE html>
<html>
  <head>
    <title>Экскурсии Украины</title>
    <meta charset="utf-8">
    <!-- Bootstrap -->
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'bootstrap/css/bootstrap.min.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'css/main.layout.css'); ?>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="http://excursion.no-ip.info//bootstrap/js/bootstrap.min.js"></script>
  </head>
  <body>
      <?php echo $this->layout()->content; ?>
  </body>
</html>